name: Run Daily Task

on:
  schedule:
    - cron: '0 9 * * *' # تشغيل الكود يوميًا في الساعة 9 صباحًا بتوقيت UTC
  workflow_dispatch:

jobs:
  run_task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0'

      - name: Run C# script
        run: |
          dotnet run --project path/to/your/project
